"""phase 2.3 shiprocket courier sync fields

Revision ID: 1b440c092593
Revises: 54ebf7a087e2
Create Date: 2026-08-23 20:09:26.594122
"""

from __future__ import annotations

from collections.abc import Sequence

import app.db.base
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1b440c092593"
down_revision: str | None = "54ebf7a087e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # All additive/nullable — existing manually-created couriers are
    # unaffected (source_system/external_id stay NULL for them).
    op.add_column("couriers", sa.Column("source_system", sa.String(length=50), nullable=True))
    op.add_column("couriers", sa.Column("external_id", sa.String(length=255), nullable=True))
    op.add_column(
        "couriers", sa.Column("external_created_at", app.db.base.AwareDateTime(), nullable=True)
    )
    op.add_column(
        "couriers", sa.Column("external_updated_at", app.db.base.AwareDateTime(), nullable=True)
    )
    op.add_column(
        "couriers", sa.Column("last_synced_at", app.db.base.AwareDateTime(), nullable=True)
    )
    op.add_column(
        "couriers", sa.Column("sync_version", sa.Integer(), server_default="1", nullable=False)
    )
    op.add_column(
        "couriers",
        sa.Column(
            "raw_external_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    op.create_index(op.f("ix_couriers_source_system"), "couriers", ["source_system"], unique=False)
    # batch mode: SQLite can't ALTER-add a constraint directly (only
    # copy-and-move); Postgres/production runs this as a plain
    # ADD CONSTRAINT either way — batch mode is a no-op passthrough there.
    with op.batch_alter_table("couriers") as batch_op:
        batch_op.create_unique_constraint(
            "uq_couriers_source_external_id", ["source_system", "external_id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("couriers") as batch_op:
        batch_op.drop_constraint("uq_couriers_source_external_id", type_="unique")
    op.drop_index(op.f("ix_couriers_source_system"), table_name="couriers")
    op.drop_column("couriers", "raw_external_payload")
    op.drop_column("couriers", "sync_version")
    op.drop_column("couriers", "last_synced_at")
    op.drop_column("couriers", "external_updated_at")
    op.drop_column("couriers", "external_created_at")
    op.drop_column("couriers", "external_id")
    op.drop_column("couriers", "source_system")
    # ### end Alembic commands ###
