"""phase 2.1 integration and sync foundation

Revision ID: 4d60488e0bdb
Revises: abbf8b3ee1d0
Create Date: 2026-08-23 18:26:28.273127
"""

from __future__ import annotations

from collections.abc import Sequence

import app.db.base
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4d60488e0bdb"
down_revision: str | None = "abbf8b3ee1d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Enum types created explicitly once each (create_type=False on every
    # column below) — same pattern as abbf8b3ee1d0, avoiding a duplicate
    # CREATE TYPE from create_table's implicit handling.
    bind = op.get_bind()
    postgresql.ENUM("ecommerce", "courier", "messaging", "social", name="integration_type").create(
        bind, checkfirst=True
    )
    postgresql.ENUM(
        "connected", "disconnected", "error", "syncing", "disabled", name="integration_status"
    ).create(bind, checkfirst=True)
    postgresql.ENUM("full", "incremental", "webhook", name="sync_type").create(
        bind, checkfirst=True
    )
    postgresql.ENUM(
        "queued", "running", "completed", "partial", "failed", "cancelled", name="sync_job_status"
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        "received", "processing", "processed", "failed", "ignored", name="webhook_event_status"
    ).create(bind, checkfirst=True)

    op.create_table(
        "integrations",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "ecommerce",
                "courier",
                "messaging",
                "social",
                name="integration_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "connected",
                "disconnected",
                "error",
                "syncing",
                "disabled",
                name="integration_status",
                create_type=False,
            ),
            server_default="disconnected",
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "configuration",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("last_sync_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("last_successful_sync_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("last_failure_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("last_failure_message", sa.String(length=500), nullable=True),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at", app.db.base.AwareDateTime(), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", app.db.base.AwareDateTime(), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_integrations_code"), "integrations", ["code"], unique=True)
    op.create_index(op.f("ix_integrations_status"), "integrations", ["status"], unique=False)

    op.create_table(
        "sync_jobs",
        sa.Column("integration_id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "sync_type",
            postgresql.ENUM("full", "incremental", "webhook", name="sync_type", create_type=False),
            nullable=False,
        ),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "queued",
                "running",
                "completed",
                "partial",
                "failed",
                "cancelled",
                name="sync_job_status",
                create_type=False,
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("started_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("completed_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("records_received", sa.Integer(), server_default="0", nullable=False),
        sa.Column("records_created", sa.Integer(), server_default="0", nullable=False),
        sa.Column("records_updated", sa.Integer(), server_default="0", nullable=False),
        sa.Column("records_skipped", sa.Integer(), server_default="0", nullable=False),
        sa.Column("records_failed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "job_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at", app.db.base.AwareDateTime(), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", app.db.base.AwareDateTime(), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["integration_id"], ["integrations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sync_jobs_entity_type"), "sync_jobs", ["entity_type"], unique=False)
    op.create_index(
        op.f("ix_sync_jobs_integration_id"), "sync_jobs", ["integration_id"], unique=False
    )
    op.create_index(op.f("ix_sync_jobs_status"), "sync_jobs", ["status"], unique=False)

    op.create_table(
        "webhook_events",
        sa.Column("integration_id", app.db.base.GUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("external_event_id", sa.String(length=255), nullable=False),
        sa.Column("external_resource_id", sa.String(length=255), nullable=True),
        sa.Column("received_at", app.db.base.AwareDateTime(), nullable=False),
        sa.Column("processed_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "received",
                "processing",
                "processed",
                "failed",
                "ignored",
                name="webhook_event_status",
                create_type=False,
            ),
            server_default="received",
            nullable=False,
        ),
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at", app.db.base.AwareDateTime(), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", app.db.base.AwareDateTime(), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["integration_id"], ["integrations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "integration_id", "external_event_id", name="uq_webhook_events_integration_external"
        ),
    )
    op.create_index(
        op.f("ix_webhook_events_external_resource_id"),
        "webhook_events",
        ["external_resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_events_integration_id"), "webhook_events", ["integration_id"], unique=False
    )
    op.create_index(op.f("ix_webhook_events_status"), "webhook_events", ["status"], unique=False)

    op.create_table(
        "sync_errors",
        sa.Column("sync_job_id", app.db.base.GUID(), nullable=False),
        sa.Column("integration_id", app.db.base.GUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("error_type", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.String(length=1000), nullable=False),
        sa.Column("payload_reference", sa.String(length=255), nullable=True),
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("resolved", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("resolved_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at", app.db.base.AwareDateTime(), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", app.db.base.AwareDateTime(), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["integration_id"], ["integrations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sync_job_id"], ["sync_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sync_errors_external_id"), "sync_errors", ["external_id"], unique=False
    )
    op.create_index(
        op.f("ix_sync_errors_integration_id"), "sync_errors", ["integration_id"], unique=False
    )
    op.create_index(op.f("ix_sync_errors_resolved"), "sync_errors", ["resolved"], unique=False)
    op.create_index(
        op.f("ix_sync_errors_sync_job_id"), "sync_errors", ["sync_job_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sync_errors_sync_job_id"), table_name="sync_errors")
    op.drop_index(op.f("ix_sync_errors_resolved"), table_name="sync_errors")
    op.drop_index(op.f("ix_sync_errors_integration_id"), table_name="sync_errors")
    op.drop_index(op.f("ix_sync_errors_external_id"), table_name="sync_errors")
    op.drop_table("sync_errors")
    op.drop_index(op.f("ix_webhook_events_status"), table_name="webhook_events")
    op.drop_index(op.f("ix_webhook_events_integration_id"), table_name="webhook_events")
    op.drop_index(op.f("ix_webhook_events_external_resource_id"), table_name="webhook_events")
    op.drop_table("webhook_events")
    op.drop_index(op.f("ix_sync_jobs_status"), table_name="sync_jobs")
    op.drop_index(op.f("ix_sync_jobs_integration_id"), table_name="sync_jobs")
    op.drop_index(op.f("ix_sync_jobs_entity_type"), table_name="sync_jobs")
    op.drop_table("sync_jobs")
    op.drop_index(op.f("ix_integrations_status"), table_name="integrations")
    op.drop_index(op.f("ix_integrations_code"), table_name="integrations")
    op.drop_table("integrations")

    bind = op.get_bind()
    postgresql.ENUM(name="webhook_event_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="sync_job_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="sync_type").drop(bind, checkfirst=True)
    postgresql.ENUM(name="integration_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="integration_type").drop(bind, checkfirst=True)
    # ### end Alembic commands ###
