"""phase 2.2 shopify sync fields

Revision ID: 54ebf7a087e2
Revises: 4d60488e0bdb
Create Date: 2026-08-23 19:17:42.810300
"""

from __future__ import annotations

from collections.abc import Sequence

import app.db.base
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "54ebf7a087e2"
down_revision: str | None = "4d60488e0bdb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # All additive/nullable — existing rows (manually created before
    # Shopify sync existed) are unaffected.
    op.add_column("order_items", sa.Column("source_system", sa.String(length=50), nullable=True))
    op.add_column("order_items", sa.Column("external_id", sa.String(length=255), nullable=True))
    op.add_column(
        "order_items",
        sa.Column("external_created_at", app.db.base.AwareDateTime(), nullable=True),
    )
    op.add_column(
        "order_items",
        sa.Column("external_updated_at", app.db.base.AwareDateTime(), nullable=True),
    )
    op.add_column(
        "order_items", sa.Column("last_synced_at", app.db.base.AwareDateTime(), nullable=True)
    )
    op.add_column(
        "order_items",
        sa.Column("sync_version", sa.Integer(), server_default="1", nullable=False),
    )
    op.add_column(
        "order_items",
        sa.Column(
            "raw_external_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_order_items_source_system"), "order_items", ["source_system"], unique=False
    )
    # batch mode: SQLite can't ALTER-add a constraint directly (only
    # copy-and-move); Postgres/production runs this as a plain
    # ADD CONSTRAINT either way — batch mode is a no-op passthrough there.
    with op.batch_alter_table("order_items") as batch_op:
        batch_op.create_unique_constraint(
            "uq_order_items_source_external_id", ["source_system", "external_id"]
        )
    op.add_column(
        "orders",
        sa.Column(
            "shipping_address",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    op.add_column(
        "orders",
        sa.Column(
            "billing_address",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    op.add_column("product_variants", sa.Column("barcode", sa.String(length=64), nullable=True))
    op.add_column(
        "product_variants",
        sa.Column(
            "options",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    op.add_column("products", sa.Column("product_type", sa.String(length=120), nullable=True))
    op.add_column("products", sa.Column("tags", sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "tags")
    op.drop_column("products", "product_type")
    op.drop_column("product_variants", "options")
    op.drop_column("product_variants", "barcode")
    op.drop_column("orders", "billing_address")
    op.drop_column("orders", "shipping_address")
    with op.batch_alter_table("order_items") as batch_op:
        batch_op.drop_constraint("uq_order_items_source_external_id", type_="unique")
    op.drop_index(op.f("ix_order_items_source_system"), table_name="order_items")
    op.drop_column("order_items", "raw_external_payload")
    op.drop_column("order_items", "sync_version")
    op.drop_column("order_items", "last_synced_at")
    op.drop_column("order_items", "external_updated_at")
    op.drop_column("order_items", "external_created_at")
    op.drop_column("order_items", "external_id")
    op.drop_column("order_items", "source_system")
    # ### end Alembic commands ###
