"""phase 1 core oms schema

Revision ID: abbf8b3ee1d0
Revises:
Create Date: 2026-08-23 16:34:48.150524
"""

from __future__ import annotations

from collections.abc import Sequence

import app.db.base
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "abbf8b3ee1d0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Enum types are shared across multiple tables below — create each
    # once, explicitly, rather than relying on create_table's implicit
    # (and here, duplicate) CREATE TYPE.
    bind = op.get_bind()
    postgresql.ENUM("active", "draft", "archived", name="product_status").create(
        bind, checkfirst=True
    )
    postgresql.ENUM("shipping", "billing", "other", name="address_type").create(
        bind, checkfirst=True
    )
    postgresql.ENUM("cod", "prepaid", "other", name="payment_type").create(bind, checkfirst=True)
    postgresql.ENUM(
        "pending",
        "authorized",
        "paid",
        "failed",
        "refunded",
        "partially_refunded",
        name="payment_status",
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        "pending",
        "confirmed",
        "processing",
        "packed",
        "shipped",
        "delivered",
        "cancelled",
        name="order_status",
    ).create(bind, checkfirst=True)
    postgresql.ENUM("unfulfilled", "partial", "fulfilled", name="fulfillment_status").create(
        bind, checkfirst=True
    )
    postgresql.ENUM("none", "requested", "cancelled", name="cancellation_status").create(
        bind, checkfirst=True
    )
    postgresql.ENUM(
        "pending",
        "picked_up",
        "in_transit",
        "out_for_delivery",
        "delivered",
        "ndr",
        "rto_initiated",
        "rto_delivered",
        "cancelled",
        name="shipment_status",
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        "on_time", "at_risk", "delayed", "unknown", name="shipment_delay_status"
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        "open",
        "customer_contacted",
        "reattempt_scheduled",
        "resolved",
        "rto_initiated",
        name="ndr_status",
    ).create(bind, checkfirst=True)
    postgresql.ENUM("initiated", "in_transit", "received", "cancelled", name="rto_status").create(
        bind, checkfirst=True
    )
    postgresql.ENUM(
        "requested",
        "approved",
        "rejected",
        "in_transit",
        "received",
        "completed",
        "cancelled",
        name="return_status",
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        "pending", "processing", "completed", "failed", "cancelled", name="refund_status"
    ).create(bind, checkfirst=True)

    op.create_table(
        "couriers",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "courier_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_couriers_code"), "couriers", ["code"], unique=True)
    op.create_table(
        "customers",
        sa.Column("shopify_customer_id", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=120), nullable=True),
        sa.Column("last_name", sa.String(length=120), nullable=True),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("alternate_phone", sa.String(length=32), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("source_system", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("external_created_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("external_updated_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("last_synced_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("sync_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "raw_external_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_system", "external_id", name="uq_customers_source_external_id"),
    )
    op.create_index(op.f("ix_customers_email"), "customers", ["email"], unique=False)
    op.create_index(op.f("ix_customers_phone"), "customers", ["phone"], unique=False)
    op.create_index(
        op.f("ix_customers_shopify_customer_id"), "customers", ["shopify_customer_id"], unique=True
    )
    op.create_index(
        op.f("ix_customers_source_system"), "customers", ["source_system"], unique=False
    )
    op.create_table(
        "permissions",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("module", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permissions_code"), "permissions", ["code"], unique=True)
    op.create_index(op.f("ix_permissions_module"), "permissions", ["module"], unique=False)
    op.create_table(
        "products",
        sa.Column("shopify_product_id", sa.String(length=64), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM("active", "draft", "archived", name="product_status", create_type=False),
            nullable=False,
        ),
        sa.Column("vendor", sa.String(length=255), nullable=True),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("source_system", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("external_created_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("external_updated_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("last_synced_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("sync_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "raw_external_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_system", "external_id", name="uq_products_source_external_id"),
    )
    op.create_index(
        op.f("ix_products_shopify_product_id"), "products", ["shopify_product_id"], unique=True
    )
    op.create_index(op.f("ix_products_source_system"), "products", ["source_system"], unique=False)
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_superuser", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("user_id", app.db.base.GUID(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column(
            "previous_value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "new_value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column(
            "audit_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "customer_addresses",
        sa.Column("customer_id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "address_type",
            postgresql.ENUM("shipping", "billing", "other", name="address_type", create_type=False),
            nullable=False,
        ),
        sa.Column("line1", sa.String(length=255), nullable=False),
        sa.Column("line2", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("state", sa.String(length=120), nullable=True),
        sa.Column("country", sa.String(length=120), server_default="India", nullable=False),
        sa.Column("pin_code", sa.String(length=16), nullable=False),
        sa.Column("landmark", sa.String(length=255), nullable=True),
        sa.Column("contact_name", sa.String(length=255), nullable=True),
        sa.Column("contact_phone", sa.String(length=32), nullable=True),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("source_system", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("external_created_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("external_updated_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("last_synced_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("sync_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "raw_external_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_system", "external_id", name="uq_customer_addresses_source_external_id"
        ),
    )
    op.create_index(
        op.f("ix_customer_addresses_customer_id"),
        "customer_addresses",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_addresses_source_system"),
        "customer_addresses",
        ["source_system"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("order_number", sa.String(length=64), nullable=False),
        sa.Column("shopify_order_id", sa.String(length=64), nullable=True),
        sa.Column("customer_id", app.db.base.GUID(), nullable=True),
        sa.Column("order_datetime", app.db.base.AwareDateTime(), nullable=False),
        sa.Column("currency", sa.String(length=8), server_default="INR", nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("shipping_charge", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "payment_type",
            postgresql.ENUM("cod", "prepaid", "other", name="payment_type", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "payment_status",
            postgresql.ENUM(
                "pending",
                "authorized",
                "paid",
                "failed",
                "refunded",
                "partially_refunded",
                name="payment_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "confirmed",
                "processing",
                "packed",
                "shipped",
                "delivered",
                "cancelled",
                name="order_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "fulfillment_status",
            postgresql.ENUM(
                "unfulfilled", "partial", "fulfilled", name="fulfillment_status", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "cancellation_status",
            postgresql.ENUM(
                "none", "requested", "cancelled", name="cancellation_status", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("source_system", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("external_created_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("external_updated_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("last_synced_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("sync_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "raw_external_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_system", "external_id", name="uq_orders_source_external_id"),
    )
    op.create_index(op.f("ix_orders_customer_id"), "orders", ["customer_id"], unique=False)
    op.create_index(op.f("ix_orders_order_number"), "orders", ["order_number"], unique=True)
    op.create_index(op.f("ix_orders_payment_status"), "orders", ["payment_status"], unique=False)
    op.create_index(op.f("ix_orders_shopify_order_id"), "orders", ["shopify_order_id"], unique=True)
    op.create_index(op.f("ix_orders_source_system"), "orders", ["source_system"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_table(
        "product_variants",
        sa.Column("product_id", app.db.base.GUID(), nullable=False),
        sa.Column("shopify_variant_id", sa.String(length=64), nullable=True),
        sa.Column("sku", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("compare_at_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("inventory_quantity", sa.Integer(), server_default="0", nullable=False),
        sa.Column("weight", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM("active", "draft", "archived", name="product_status", create_type=False),
            nullable=False,
        ),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("source_system", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("external_created_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("external_updated_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("last_synced_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("sync_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "raw_external_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_system", "external_id", name="uq_product_variants_source_external_id"
        ),
    )
    op.create_index(
        op.f("ix_product_variants_product_id"), "product_variants", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_variants_shopify_variant_id"),
        "product_variants",
        ["shopify_variant_id"],
        unique=True,
    )
    op.create_index(op.f("ix_product_variants_sku"), "product_variants", ["sku"], unique=True)
    op.create_index(
        op.f("ix_product_variants_source_system"),
        "product_variants",
        ["source_system"],
        unique=False,
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("user_id", app.db.base.GUID(), nullable=False),
        sa.Column("expires_at", app.db.base.AwareDateTime(), nullable=False),
        sa.Column("revoked_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refresh_tokens_jti"), "refresh_tokens", ["jti"], unique=True)
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "role_permissions",
        sa.Column("role_id", app.db.base.GUID(), nullable=False),
        sa.Column("permission_id", app.db.base.GUID(), nullable=False),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_id", "permission_id", name="uq_role_permissions_role_permission"),
    )
    op.create_index(
        op.f("ix_role_permissions_permission_id"),
        "role_permissions",
        ["permission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_permissions_role_id"), "role_permissions", ["role_id"], unique=False
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", app.db.base.GUID(), nullable=False),
        sa.Column("role_id", app.db.base.GUID(), nullable=False),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id", name="uq_user_roles_user_role"),
    )
    op.create_index(op.f("ix_user_roles_role_id"), "user_roles", ["role_id"], unique=False)
    op.create_index(op.f("ix_user_roles_user_id"), "user_roles", ["user_id"], unique=False)
    op.create_table(
        "order_events",
        sa.Column("order_id", app.db.base.GUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=50), server_default="system", nullable=False),
        sa.Column("actor_user_id", app.db.base.GUID(), nullable=True),
        sa.Column(
            "event_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "raw_external_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_events_created_at"), "order_events", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_order_events_order_id"), "order_events", ["order_id"], unique=False)
    op.create_table(
        "order_items",
        sa.Column("order_id", app.db.base.GUID(), nullable=False),
        sa.Column("product_variant_id", app.db.base.GUID(), nullable=True),
        sa.Column("sku", sa.String(length=120), nullable=False),
        sa.Column("product_name", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["product_variant_id"], ["product_variants.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False)
    op.create_index(
        op.f("ix_order_items_product_variant_id"),
        "order_items",
        ["product_variant_id"],
        unique=False,
    )
    op.create_table(
        "payments",
        sa.Column("order_id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "payment_type",
            postgresql.ENUM("cod", "prepaid", "other", name="payment_type", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "authorized",
                "paid",
                "failed",
                "refunded",
                "partially_refunded",
                name="payment_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=8), server_default="INR", nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=True),
        sa.Column("external_transaction_id", sa.String(length=255), nullable=True),
        sa.Column("paid_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column(
            "payment_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("source_system", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("external_created_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("external_updated_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("last_synced_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("sync_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "raw_external_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_system", "external_id", name="uq_payments_source_external_id"),
    )
    op.create_index(
        op.f("ix_payments_external_transaction_id"),
        "payments",
        ["external_transaction_id"],
        unique=False,
    )
    op.create_index(op.f("ix_payments_order_id"), "payments", ["order_id"], unique=False)
    op.create_index(op.f("ix_payments_source_system"), "payments", ["source_system"], unique=False)
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_table(
        "shipments",
        sa.Column("order_id", app.db.base.GUID(), nullable=False),
        sa.Column("shiprocket_shipment_id", sa.String(length=64), nullable=True),
        sa.Column("awb", sa.String(length=64), nullable=True),
        sa.Column("courier_id", app.db.base.GUID(), nullable=True),
        sa.Column(
            "current_status",
            postgresql.ENUM(
                "pending",
                "picked_up",
                "in_transit",
                "out_for_delivery",
                "delivered",
                "ndr",
                "rto_initiated",
                "rto_delivered",
                "cancelled",
                name="shipment_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "delay_status",
            postgresql.ENUM(
                "on_time",
                "at_risk",
                "delayed",
                "unknown",
                name="shipment_delay_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "ndr_status",
            postgresql.ENUM(
                "open",
                "customer_contacted",
                "reattempt_scheduled",
                "resolved",
                "rto_initiated",
                name="ndr_status",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "rto_status",
            postgresql.ENUM(
                "initiated",
                "in_transit",
                "received",
                "cancelled",
                name="rto_status",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("pickup_date", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("expected_delivery_date", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("actual_delivery_date", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("current_location", sa.String(length=255), nullable=True),
        sa.Column("last_tracking_update_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("source_system", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("external_created_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("external_updated_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("last_synced_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("sync_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "raw_external_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["courier_id"], ["couriers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_system", "external_id", name="uq_shipments_source_external_id"),
    )
    op.create_index(op.f("ix_shipments_awb"), "shipments", ["awb"], unique=True)
    op.create_index(op.f("ix_shipments_courier_id"), "shipments", ["courier_id"], unique=False)
    op.create_index(
        op.f("ix_shipments_current_status"), "shipments", ["current_status"], unique=False
    )
    op.create_index(
        op.f("ix_shipments_expected_delivery_date"),
        "shipments",
        ["expected_delivery_date"],
        unique=False,
    )
    op.create_index(op.f("ix_shipments_order_id"), "shipments", ["order_id"], unique=False)
    op.create_index(
        op.f("ix_shipments_shiprocket_shipment_id"),
        "shipments",
        ["shiprocket_shipment_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_shipments_source_system"), "shipments", ["source_system"], unique=False
    )
    op.create_table(
        "ndrs",
        sa.Column("shipment_id", app.db.base.GUID(), nullable=False),
        sa.Column("order_id", app.db.base.GUID(), nullable=False),
        sa.Column("courier_id", app.db.base.GUID(), nullable=True),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("normalized_reason", sa.String(length=100), nullable=True),
        sa.Column("external_reason", sa.String(length=255), nullable=True),
        sa.Column("attempt_number", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "open",
                "customer_contacted",
                "reattempt_scheduled",
                "resolved",
                "rto_initiated",
                name="ndr_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("customer_response", sa.Text(), nullable=True),
        sa.Column("reattempt_status", sa.String(length=100), nullable=True),
        sa.Column("reattempt_date", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("source_system", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("external_created_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("external_updated_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("last_synced_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("sync_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "raw_external_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["courier_id"], ["couriers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shipment_id"], ["shipments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_system", "external_id", name="uq_ndrs_source_external_id"),
    )
    op.create_index(op.f("ix_ndrs_courier_id"), "ndrs", ["courier_id"], unique=False)
    op.create_index(op.f("ix_ndrs_normalized_reason"), "ndrs", ["normalized_reason"], unique=False)
    op.create_index(op.f("ix_ndrs_order_id"), "ndrs", ["order_id"], unique=False)
    op.create_index(op.f("ix_ndrs_shipment_id"), "ndrs", ["shipment_id"], unique=False)
    op.create_index(op.f("ix_ndrs_source_system"), "ndrs", ["source_system"], unique=False)
    op.create_index(op.f("ix_ndrs_status"), "ndrs", ["status"], unique=False)
    op.create_table(
        "payment_transactions",
        sa.Column("payment_id", app.db.base.GUID(), nullable=False),
        sa.Column("gateway", sa.String(length=100), nullable=True),
        sa.Column("gateway_transaction_id", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "authorized",
                "paid",
                "failed",
                "refunded",
                "partially_refunded",
                name="payment_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.ForeignKeyConstraint(["payment_id"], ["payments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_transactions_gateway_transaction_id"),
        "payment_transactions",
        ["gateway_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_transactions_payment_id"),
        "payment_transactions",
        ["payment_id"],
        unique=False,
    )
    op.create_table(
        "returns",
        sa.Column("order_id", app.db.base.GUID(), nullable=False),
        sa.Column("order_item_id", app.db.base.GUID(), nullable=True),
        sa.Column("customer_id", app.db.base.GUID(), nullable=True),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "requested",
                "approved",
                "rejected",
                "in_transit",
                "received",
                "completed",
                "cancelled",
                name="return_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Integer(), server_default="1", nullable=False),
        sa.Column("requested_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("approved_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("received_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("completed_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("source_system", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("external_created_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("external_updated_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("last_synced_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("sync_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "raw_external_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["order_item_id"], ["order_items.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_system", "external_id", name="uq_returns_source_external_id"),
    )
    op.create_index(op.f("ix_returns_customer_id"), "returns", ["customer_id"], unique=False)
    op.create_index(op.f("ix_returns_order_id"), "returns", ["order_id"], unique=False)
    op.create_index(op.f("ix_returns_order_item_id"), "returns", ["order_item_id"], unique=False)
    op.create_index(op.f("ix_returns_source_system"), "returns", ["source_system"], unique=False)
    op.create_index(op.f("ix_returns_status"), "returns", ["status"], unique=False)
    op.create_table(
        "rtos",
        sa.Column("shipment_id", app.db.base.GUID(), nullable=False),
        sa.Column("order_id", app.db.base.GUID(), nullable=False),
        sa.Column("courier_id", app.db.base.GUID(), nullable=True),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("normalized_reason", sa.String(length=100), nullable=True),
        sa.Column("external_reason", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "initiated",
                "in_transit",
                "received",
                "cancelled",
                name="rto_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("initiated_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("completed_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "rto_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("source_system", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("external_created_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("external_updated_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("last_synced_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("sync_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "raw_external_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["courier_id"], ["couriers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shipment_id"], ["shipments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_system", "external_id", name="uq_rtos_source_external_id"),
    )
    op.create_index(op.f("ix_rtos_courier_id"), "rtos", ["courier_id"], unique=False)
    op.create_index(op.f("ix_rtos_normalized_reason"), "rtos", ["normalized_reason"], unique=False)
    op.create_index(op.f("ix_rtos_order_id"), "rtos", ["order_id"], unique=False)
    op.create_index(op.f("ix_rtos_shipment_id"), "rtos", ["shipment_id"], unique=False)
    op.create_index(op.f("ix_rtos_source_system"), "rtos", ["source_system"], unique=False)
    op.create_index(op.f("ix_rtos_status"), "rtos", ["status"], unique=False)
    op.create_table(
        "shipment_events",
        sa.Column("shipment_id", app.db.base.GUID(), nullable=False),
        sa.Column("external_event_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("event_timestamp", app.db.base.AwareDateTime(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("courier_name", sa.String(length=255), nullable=True),
        sa.Column("source", sa.String(length=50), server_default="system", nullable=False),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.ForeignKeyConstraint(["shipment_id"], ["shipments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "shipment_id", "external_event_id", name="uq_shipment_events_shipment_external_event"
        ),
    )
    op.create_index(
        op.f("ix_shipment_events_event_timestamp"),
        "shipment_events",
        ["event_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_shipment_events_shipment_id"), "shipment_events", ["shipment_id"], unique=False
    )
    op.create_table(
        "refunds",
        sa.Column("order_id", app.db.base.GUID(), nullable=False),
        sa.Column("payment_id", app.db.base.GUID(), nullable=True),
        sa.Column("return_id", app.db.base.GUID(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "processing",
                "completed",
                "failed",
                "cancelled",
                name="refund_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("initiated_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("completed_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column(
            "refund_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("id", app.db.base.GUID(), nullable=False),
        sa.Column(
            "created_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.base.AwareDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("source_system", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("external_created_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("external_updated_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("last_synced_at", app.db.base.AwareDateTime(), nullable=True),
        sa.Column("sync_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "raw_external_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["payment_id"], ["payments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["return_id"], ["returns.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_system", "external_id", name="uq_refunds_source_external_id"),
    )
    op.create_index(op.f("ix_refunds_order_id"), "refunds", ["order_id"], unique=False)
    op.create_index(op.f("ix_refunds_payment_id"), "refunds", ["payment_id"], unique=False)
    op.create_index(op.f("ix_refunds_return_id"), "refunds", ["return_id"], unique=False)
    op.create_index(op.f("ix_refunds_source_system"), "refunds", ["source_system"], unique=False)
    op.create_index(op.f("ix_refunds_status"), "refunds", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refunds_status"), table_name="refunds")
    op.drop_index(op.f("ix_refunds_source_system"), table_name="refunds")
    op.drop_index(op.f("ix_refunds_return_id"), table_name="refunds")
    op.drop_index(op.f("ix_refunds_payment_id"), table_name="refunds")
    op.drop_index(op.f("ix_refunds_order_id"), table_name="refunds")
    op.drop_table("refunds")
    op.drop_index(op.f("ix_shipment_events_shipment_id"), table_name="shipment_events")
    op.drop_index(op.f("ix_shipment_events_event_timestamp"), table_name="shipment_events")
    op.drop_table("shipment_events")
    op.drop_index(op.f("ix_rtos_status"), table_name="rtos")
    op.drop_index(op.f("ix_rtos_source_system"), table_name="rtos")
    op.drop_index(op.f("ix_rtos_shipment_id"), table_name="rtos")
    op.drop_index(op.f("ix_rtos_order_id"), table_name="rtos")
    op.drop_index(op.f("ix_rtos_normalized_reason"), table_name="rtos")
    op.drop_index(op.f("ix_rtos_courier_id"), table_name="rtos")
    op.drop_table("rtos")
    op.drop_index(op.f("ix_returns_status"), table_name="returns")
    op.drop_index(op.f("ix_returns_source_system"), table_name="returns")
    op.drop_index(op.f("ix_returns_order_item_id"), table_name="returns")
    op.drop_index(op.f("ix_returns_order_id"), table_name="returns")
    op.drop_index(op.f("ix_returns_customer_id"), table_name="returns")
    op.drop_table("returns")
    op.drop_index(op.f("ix_payment_transactions_payment_id"), table_name="payment_transactions")
    op.drop_index(
        op.f("ix_payment_transactions_gateway_transaction_id"), table_name="payment_transactions"
    )
    op.drop_table("payment_transactions")
    op.drop_index(op.f("ix_ndrs_status"), table_name="ndrs")
    op.drop_index(op.f("ix_ndrs_source_system"), table_name="ndrs")
    op.drop_index(op.f("ix_ndrs_shipment_id"), table_name="ndrs")
    op.drop_index(op.f("ix_ndrs_order_id"), table_name="ndrs")
    op.drop_index(op.f("ix_ndrs_normalized_reason"), table_name="ndrs")
    op.drop_index(op.f("ix_ndrs_courier_id"), table_name="ndrs")
    op.drop_table("ndrs")
    op.drop_index(op.f("ix_shipments_source_system"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_shiprocket_shipment_id"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_order_id"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_expected_delivery_date"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_current_status"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_courier_id"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_awb"), table_name="shipments")
    op.drop_table("shipments")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_source_system"), table_name="payments")
    op.drop_index(op.f("ix_payments_order_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_external_transaction_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_order_items_product_variant_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_order_events_order_id"), table_name="order_events")
    op.drop_index(op.f("ix_order_events_created_at"), table_name="order_events")
    op.drop_table("order_events")
    op.drop_index(op.f("ix_user_roles_user_id"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_role_id"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_role_permissions_role_id"), table_name="role_permissions")
    op.drop_index(op.f("ix_role_permissions_permission_id"), table_name="role_permissions")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_jti"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_product_variants_source_system"), table_name="product_variants")
    op.drop_index(op.f("ix_product_variants_sku"), table_name="product_variants")
    op.drop_index(op.f("ix_product_variants_shopify_variant_id"), table_name="product_variants")
    op.drop_index(op.f("ix_product_variants_product_id"), table_name="product_variants")
    op.drop_table("product_variants")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_source_system"), table_name="orders")
    op.drop_index(op.f("ix_orders_shopify_order_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_payment_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_order_number"), table_name="orders")
    op.drop_index(op.f("ix_orders_customer_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_customer_addresses_source_system"), table_name="customer_addresses")
    op.drop_index(op.f("ix_customer_addresses_customer_id"), table_name="customer_addresses")
    op.drop_table("customer_addresses")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_index(op.f("ix_products_source_system"), table_name="products")
    op.drop_index(op.f("ix_products_shopify_product_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_permissions_module"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_code"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_customers_source_system"), table_name="customers")
    op.drop_index(op.f("ix_customers_shopify_customer_id"), table_name="customers")
    op.drop_index(op.f("ix_customers_phone"), table_name="customers")
    op.drop_index(op.f("ix_customers_email"), table_name="customers")
    op.drop_table("customers")
    op.drop_index(op.f("ix_couriers_code"), table_name="couriers")
    op.drop_table("couriers")

    # Drop the enum types created explicitly in upgrade() — table drops
    # above don't remove them since they were created with checkfirst=True
    # outside of any single column's ownership.
    bind = op.get_bind()
    postgresql.ENUM(name="product_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="address_type").drop(bind, checkfirst=True)
    postgresql.ENUM(name="payment_type").drop(bind, checkfirst=True)
    postgresql.ENUM(name="payment_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="order_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="fulfillment_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="cancellation_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="shipment_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="shipment_delay_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="ndr_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="rto_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="return_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="refund_status").drop(bind, checkfirst=True)
    # ### end Alembic commands ###
